version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres-dev:
    hostname: localhost
    image: postgres:latest
    container_name: local_server
    restart: unless-stopped
    environment:
      POSTGRES_USER: irfanmaulana007
      POSTGRES_PASSWORD: password
      POSTGRES_DB: simagis
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - pos-warehouse-dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for Development
  # redis-dev:
  #   image: redis:7-alpine
  #   container_name: pos-warehouse-redis-dev
  #   restart: unless-stopped
  #   ports:
  #     - "6380:6379"  # Different port to avoid conflicts
  #   volumes:
  #     - redis_dev_data:/data
  #   networks:
  #     - pos-warehouse-dev-network
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3

  # pgAdmin for Database Management
  # pgadmin:
  #   image: dpage/pgadmin4:latest
  #   container_name: pos-warehouse-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   ports:
  #     - "5050:80"
  #   volumes:
  #     - pgadmin_data:/var/lib/pgadmin
  #   depends_on:
  #     - postgres-dev
  #   networks:
  #     - pos-warehouse-dev-network

volumes:
  postgres_dev_data:
    driver: local
  # redis_dev_data:
  #   driver: local
  # pgadmin_data:
  #   driver: local

networks:
  pos-warehouse-dev-network:
    driver: bridge