import { MenuEnum, PriceTypeEnum, PrismaClient, RoleEnum, SubMenuEnum } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function seedInitialData() {
  await prisma.bank.createMany({
    skipDuplicates: true,
    data: [
      { code: '002', name: 'Bank BRI' },
      { code: '008', name: 'Bank Mandiri' },
      { code: '009', name: 'Bank BNI' },
      { code: '011', name: 'Bank Danamon' },
      { code: '013', name: 'Bank Permata' },
      { code: '014', name: 'Bank BCA' },
      { code: '016', name: 'Bank Maybank Indonesia' },
      { code: '019', name: 'Bank Panin' },
      { code: '022', name: 'CIMB Niaga' },
      { code: '023', name: 'Bank UOB Indonesia' },
      { code: '028', name: 'Bank OCBC NISP' },
      { code: '031', name: 'Citi Bank' },
      { code: '036', name: 'Bank CCB' },
      { code: '037', name: 'Bank Artha Graha' },
      { code: '042', name: 'Bank MUFG Bank' },
      { code: '046', name: 'Bank DBS' },
      { code: '050', name: 'Standard Chartered Bank' },
      { code: '054', name: 'Bank Capital' },
      { code: '061', name: 'ANZ Indonesia' },
      { code: '069', name: 'Bank of China ' },
      { code: '076', name: 'Bank Bumi Arta' },
      { code: '087', name: 'Bank HSBC Indonesia' },
      { code: '089', name: 'Bank RABOBANK' },
      { code: '095', name: 'Bank JTrust Indonesia' },
      { code: '097', name: 'Bank Mayapada' },
      { code: '110', name: 'Bank BJB' },
      { code: '111', name: 'Bank DKI' },
      { code: '112', name: 'Bank BPD DIY' },
      { code: '113', name: 'Bank Jateng' },
      { code: '114', name: 'Bank Jatim' },
      { code: '115', name: 'Bank Jambi' },
      { code: '116', name: 'Bank Aceh' },
      { code: '117', name: 'Bank Sumut' },
      { code: '118', name: 'Bank Nagari' },
      { code: '119', name: 'Bank Riau Kepri' },
      { code: '120', name: 'Bank Sumsel Babel' },
      { code: '121', name: 'Bank Lampung' },
      { code: '122', name: 'Bank Kalsel' },
      { code: '123', name: 'Bank Kalbar' },
      { code: '124', name: 'Bank Kaltimtara' },
      { code: '125', name: 'Bank Kalteng' },
      { code: '126', name: 'Bank Sulselbar' },
      { code: '127', name: 'Bank Sulut Go' },
      { code: '128', name: 'Bank NTB Syariah' },
      { code: '129', name: 'Bank BPD Bali' },
      { code: '130', name: 'Bank NTT' },
      { code: '131', name: 'Bank Maluku Malut' },
      { code: '132', name: 'Bank Papua' },
      { code: '133', name: 'Bank Bengkulu' },
      { code: '134', name: 'Bank Sulteng' },
      { code: '135', name: 'Bank Sultra' },
      { code: '137', name: 'Bank Banten' },
      { code: '146', name: 'Bank of India Indonesia' },
      { code: '147', name: 'Bank Muamalat Indonesia' },
      { code: '151', name: 'Bank Mestika' },
      { code: '152', name: 'Bank Shinhan Indonesia' },
      { code: '153', name: 'Bank SINARMAS' },
      { code: '157', name: 'Bank Maspion Indonesia' },
      { code: '161', name: 'Bank Ganesha' },
      { code: '164', name: 'Bank ICBC Indonesia' },
      { code: '167', name: 'Bank QNB Indonesia' },
      { code: '200', name: 'Bank BTN' },
      { code: '212', name: 'Bank Woori Saudara' },
      { code: '213', name: 'Bank BTPN' },
      { code: '405', name: 'Bank Victoria Syariah' },
      { code: '422', name: 'Bank BRI Syariah' },
      { code: '425', name: 'Bank BJB Syariah' },
      { code: '426', name: 'Bank Mega' },
      { code: '427', name: 'Bank BNI Syariah' },
      { code: '441', name: 'Bank Bukopin' },
      { code: '451', name: 'Bank Syariah Mandiri' },
      { code: '472', name: 'Bank Jasa Jakarta' },
      { code: '484', name: 'Bank KEB Hana' },
      { code: '485', name: 'MNC Bank' },
      { code: '490', name: 'Bank Neo Commerce' },
      { code: '494', name: 'Bank BRI Agroniaga' },
      { code: '498', name: 'Bank SBI' },
      { code: '503', name: 'Bank Nobu' },
      { code: '506', name: 'Bank Mega Syariah' },
      { code: '513', name: 'Bank Ina Perdana' },
      { code: '517', name: 'Bank Panin Dubai Syariah' },
      { code: '520', name: 'Bank Prima Master' },
      { code: '521', name: 'Bank Syariah Bukopin' },
      { code: '523', name: 'Bank Sahabat Sampoerna' },
      { code: '526', name: 'Bank DINAR Indonesia' },
      { code: '535', name: 'Bank Kesejahteraan Ekonomi' },
      { code: '536', name: 'Bank BCA Syariah' },
      { code: '542', name: 'Bank ARTOS Indonesia' },
      { code: '547', name: 'Bank BPTN Syariah' },
      { code: '548', name: 'Bank Multiarta Sentosa' },
      { code: '553', name: 'Bank Mayora' },
      { code: '555', name: 'Bank Index Selindo' },
      { code: '564', name: 'Bank Sinar Harapan Bali' },
      { code: '566', name: 'Bank Victoria Internasional' },
      { code: '567', name: 'Bank Harda Internasional' },
      { code: '600', name: 'BPR/LSB' },
      { code: '688', name: 'BPR KS' },
      { code: '699', name: 'BPR EKA' },
      { code: '789', name: 'Indosat (Dompetku)' },
      { code: '911', name: 'Telkomsel (TCASH)' },
      { code: '945', name: 'Bank AGRIS' },
      { code: '949', name: 'Bank ChinaTrust Indonesia' },
      { code: '950', name: 'Bank Commonwealth' },
    ],
  });

  const user = await prisma.user.create({
    data: {
      code: 'USRJKT0001',
      name: 'super admin',
      password: bcrypt.hashSync('asdf', 12),
      username: 'superadmin',
      address: 'dukuh pinggir',
      balance: 0,
      discountLimit: 0,
      email: 'superadmin@gmail.com',
      phone: '08000000000',
      role: RoleEnum.SUPER_ADMIN,
    },
  });

  const branch = await prisma.branch.create({
    data: {
      code: 'JKT',
      address: 'Kebon kacang',
      name: 'Jakarta',
      priceType: PriceTypeEnum.ECER,
    },
  });

  await prisma.userBranchDetail.create({
    data: {
      branchCode: branch.code,
      userCode: user.code,
    },
  });

  await prisma.userPermission.createMany({
    skipDuplicates: true,
    data: [
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SUPER_ADMIN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.OWNER,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: true,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: true,
        create: true,
        update: true,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: true,
        create: true,
        update: true,
        delete: true,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.PIMPINAN,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.ANGGOTA,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.KASIR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.SALES,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.HEAD_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_KANTOR,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_INVENTORY,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportTransaction,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Report,
        subMenu: SubMenuEnum.ReportClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionSales,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionReturn,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Transaction,
        subMenu: SubMenuEnum.TransactionBilling,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletInventory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletCashRegister,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletExpense,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletClosing,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletDeposit,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletRestock,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Outlet,
        subMenu: SubMenuEnum.OutletStockOpname,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementBranch,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementStaff,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementMember,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementSupplier,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementPromo,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementColor,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementProductCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementExpenseCategory,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiro,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementCekGiroFailStatus,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
      {
        role: RoleEnum.STAFF_WAREHOUSE,
        menu: MenuEnum.Management,
        subMenu: SubMenuEnum.ManagementUserPermission,
        view: false,
        create: false,
        update: false,
        delete: false,
      },
    ],
  });
}

async function main() {
  try {
    await seedInitialData();
  } catch (err) {
    console.error(err);
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
